### ISSUE TITLE
dependency options

### ISSUE THREAD

**Issue by tjtnew** [reconhub/trending#11]
Dependencies that could be dropped if desired:
* [purrr] is mainly used for the nice error handling with `safely` with the added benefit of the consistent interface.  This could be replaced by using `tryCatch` with `lapply` if we wanted.
* [dplyr] `bind_rows` handles different column names by default but we could always create a wrapper around rbind if desired. 
* [ciTools] used for simulated prediction intervals.

**Comment by dirkschumacher** [comment]
I'd say to drop `purrr` and `dplyr`, if possible. `ciTools` probably needs to be replaced with our own package for prediction intervals of various models

**Comment by tjtnew** [comment]
We are now dependency free again (save base and recommended packages) ;)
