### ISSUE TITLE
Default to fitted data in predict()

### ISSUE THREAD

**Issue by thibautjombart** [reconhub/trending#8]
Currently, the `predict` method for `trending_model_fit` does not have a default `data`. To be consistent with `lm` / `glm` objects, we should probably consider having the data used for fitting as default data. Workflow would be for instance:

```r
## predictions for default data (used in fitting)
lm_model(count ~ day) %>% fit(dat) %>% predict()

## predictions for another dataset
lm_model(count ~ day) %>% fit(dat) %>% predict(other_data)


```

**Comment by tjtnew** [comment]
closed by d99252f.  We may want to revisit the output of predict but this will likely be covered when considering #9.
